# fly.toml for Backend (kapehan-api)
app = "kapehan-api"
primary_region = "sin"

[build]

[[services]]
  internal_port = 3000     # Match this to the backend's app.listen() port
  protocol = "tcp"         # Use TCP for internal communication
  # No external handlers, making the backend private